### ISSUE TITLE
Dwarf Champion cannot revert to rifle after change to pistol is upgraded

### ISSUE THREAD

**Issue by X00181735** [AdamLay/opr-army-forge#160] opened 2021-11-02 14:19 UTC
Dwarf Champion

### **1. Replace one Rifle and CCW with Pistol and CCW** 

![image](https://user-images.githubusercontent.com/91834269/139864625-4e07f588-99c8-4396-a149-786a59ebde31.png)

### **2. Replace Pistol with any upgrade, in this case combat shield**

![image](https://user-images.githubusercontent.com/91834269/139864716-6249ae0a-39c8-47ae-96f6-dce6b838a28f.png)

### **3. Revert upgrade, go back to None**

![image](https://user-images.githubusercontent.com/91834269/139864795-2a8b3f95-8a71-4781-8b61-a701430a2b8d.png)

### **4. No longer possible to revert back to Rifle and CCW**

![image](https://user-images.githubusercontent.com/91834269/139864940-6fb93a0e-bab7-4760-84fc-9e573d454387.png)

**Comment by Darguth** [comment] 2021-11-02 14:51
This is a duplicate of bug described in #145 .

**Comment by X00181735** [comment] 2021-11-02 14:54
> 
> 
> This is a duplicate of bug described in #145 .

They don't seem to operate in the same way, but perhaps the underlying cause is the same.

**Comment by AdamLay** [comment] 2021-11-02 15:07
Just double checked this one and think it is actually something different - will investigate. Thanks,

**Comment by Darguth** [comment] 2021-11-02 19:56
Fixed and tested.

**Closed by Darguth** 2021-11-02 19:56 UTC
Labels: bug
