### ISSUE TITLE
Unexpected auto-scroll upwards when tapping unit on mobile

### ISSUE THREAD

**Issue by klauskopec** [AdamLay/opr-army-forge#333] opened 2022-06-28 14:11 UTC
Minor issue: When you scroll through the available unit list on mobile and tap on any unit, the available unit list automatically scrolls back to the top of the list. Thus, when you close the unit details dialog, you'll not be at the list position where you were before, but instead need to scroll back down to get back to that position.

This can become quite tedious when you're using army forge to explore the details of a larger number of units of a potential new army you're interested in.

**Comment by AdamLay** [comment] 2022-07-01 22:12
Duplicate of #326- should be fixed

**Closed by AdamLay** 2022-07-01 22:12 UTC
